AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.

Resources:
  API:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        API:
          Type: Api
          Properties:
            Path: /hello
            Method: post
      Environment:
        Variables:
          ATLAS_URI: ${ATLAS_URI}
          AWS_BUCKET: ${AWS_BUCKET}
    Metadata:
      DockerTag: custom-lambda-go
      DockerContext: ./API
      Dockerfile: Dockerfile